default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: <%= ENV['PG_USERNAME'] || 'postgres' %>
  password: <%= ENV['PG_PASSWORD'] || 'password' %>

development:
  <<: *default
  database: your_database_development

test:
  <<: *default
  database: your_database_test

production:
  <<: *default
  database: your_database_production
  username: <%= ENV['PG_USERNAME'] %>
  password: <%= ENV['PG_PASSWORD'] %>
