name: deploy-github-actions
# トリガーの設定
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest # 実行環境の設定
    steps:
      - name: ssh and deploy
        uses: appleboy/ssh-action@master # １
        with: # 2 アクションの入力パラメータを指定
          host: ${{ secrets.SSH_HOST }} # ホスト名
          username: ${{ secrets.SSH_USERNAME }} # SSH ユーザ名
          port: ${{ secrets.SSH_PORT }} # ポート番号
          passphrase: ${{ secrets.SSH_PASSPHRASE }} # パスフレーズ
          debug: true
          script: |
            set -e
            cd /home/alma/gakushu
            git fetch origin main
            git checkout main
            git pull origin main  
            bundle install   
            bundle exec rails assets:precompile
            rm tmp/pids/server.pid
            bundle exec rails server -b 0.0.0.0 -d
